export const projectConstant = [
  {
    title: "Restaurant Site With Bootstrap5",
    imgSrc: "https://picsum.photos/id/7/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["react"],
  },
  {
    title: "AJAX Example With Numbers API",
    imgSrc: "https://picsum.photos/id/231/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["javascript", "react"],
  },
  {
    title: "Chat App CSS Illustration",
    imgSrc: "https://picsum.photos/id/29/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["javascript", "ant-design"],
  },
  {
    title: "Static Job Listings With Json",
    imgSrc: "https://picsum.photos/id/56/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["javascript"],
  },
  {
    title: "Static Job Listings With Data Attributes",
    imgSrc: "https://picsum.photos/id/47/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["javascript"],
  },
  {
    title: "Manage Landing Page",
    imgSrc: "https://picsum.photos/id/22/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["javascript"],
  },
  {
    title: "Fylo Dark Theme Landing Page",
    imgSrc: "https://picsum.photos/id/95/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["javascript"],
  },
  {
    title: "Project Tracking Intro Component",
    imgSrc: "https://picsum.photos/id/34/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["javascript"],
  },
  {
    title: "Ping Coming Soon Page",
    imgSrc: "https://picsum.photos/id/91/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["javascript", "css"],
  },
  {
    title: "Huddle Landing Page",
    imgSrc: "https://picsum.photos/id/67/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["javascript", "css"],
  },
  {
    title: "Four Card Feature Section",
    imgSrc: "https://picsum.photos/id/200/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["css"],
  },
  {
    title: "Coding Bootcamp Testimonials Slider",
    imgSrc: "https://picsum.photos/id/39/120/120",
    previewLink: "",
    codeLink: "",
    technologies: ["css"],
  },
];
